spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/db_zonas_peligrosas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

app.jwt.secret=CADENA_ALEATORIA_DE_AL_MENOS_32_CARACTERES
app.jwt.expiration=86400000
